-- A dedicated database. No reference repository or existing startup schema is touched.
CREATE TABLE IF NOT EXISTS schema_version(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS runs(id text PRIMARY KEY, name text NOT NULL, revision bigint NOT NULL DEFAULT 0, minute integer NOT NULL DEFAULT 0 CHECK(minute>=0), metadata jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS locations(run_id text REFERENCES runs(id), id text, kind text NOT NULL, capacity integer NOT NULL CHECK(capacity>0), attributes jsonb NOT NULL, PRIMARY KEY(run_id,id));
CREATE TABLE IF NOT EXISTS equipment(run_id text REFERENCES runs(id), id text, kind text NOT NULL, status text NOT NULL CHECK(status IN ('available','failed')), attributes jsonb NOT NULL, PRIMARY KEY(run_id,id));
CREATE TABLE IF NOT EXISTS commitments(run_id text REFERENCES runs(id), id text, location_id text NOT NULL, cutoff integer NOT NULL, kind text NOT NULL, attributes jsonb NOT NULL, PRIMARY KEY(run_id,id), FOREIGN KEY(run_id,location_id) REFERENCES locations(run_id,id));
CREATE TABLE IF NOT EXISTS containers(run_id text REFERENCES runs(id), id text, visit_id text NOT NULL, location_id text, commitment_id text, attributes jsonb NOT NULL, PRIMARY KEY(run_id,id), UNIQUE(run_id,visit_id), FOREIGN KEY(run_id,location_id) REFERENCES locations(run_id,id), FOREIGN KEY(run_id,commitment_id) REFERENCES commitments(run_id,id));
CREATE INDEX IF NOT EXISTS containers_location ON containers(run_id,location_id);
CREATE TABLE IF NOT EXISTS move_jobs(run_id text REFERENCES runs(id), id text, container_id text NOT NULL, source_id text NOT NULL, target_id text NOT NULL, equipment_id text NOT NULL, status text NOT NULL CHECK(status IN ('queued','running','completed')), attributes jsonb NOT NULL, PRIMARY KEY(run_id,id), FOREIGN KEY(run_id,container_id) REFERENCES containers(run_id,id), FOREIGN KEY(run_id,source_id) REFERENCES locations(run_id,id), FOREIGN KEY(run_id,target_id) REFERENCES locations(run_id,id), FOREIGN KEY(run_id,equipment_id) REFERENCES equipment(run_id,id));
CREATE INDEX IF NOT EXISTS jobs_queue ON move_jobs(run_id,status);
CREATE TABLE IF NOT EXISTS job_dependencies(run_id text, job_id text, predecessor_id text, PRIMARY KEY(run_id,job_id,predecessor_id), FOREIGN KEY(run_id,job_id) REFERENCES move_jobs(run_id,id), FOREIGN KEY(run_id,predecessor_id) REFERENCES move_jobs(run_id,id), CHECK(job_id<>predecessor_id));
CREATE TABLE IF NOT EXISTS events(id bigserial PRIMARY KEY, run_id text REFERENCES runs(id), revision bigint NOT NULL, kind text NOT NULL, entity_id text NOT NULL, valid_minute integer NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now(), command_id text, source text NOT NULL, schema_version integer NOT NULL DEFAULT 1, payload jsonb NOT NULL);
CREATE INDEX IF NOT EXISTS events_entity_time ON events(run_id,entity_id,revision DESC);
CREATE TABLE IF NOT EXISTS snapshots(run_id text REFERENCES runs(id), revision bigint, minute integer NOT NULL, state jsonb NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(run_id,revision));
CREATE TABLE IF NOT EXISTS observations(id bigserial PRIMARY KEY, run_id text REFERENCES runs(id), entity_id text NOT NULL, valid_minute integer NOT NULL, recorded_minute integer NOT NULL, revision bigint NOT NULL, value text NOT NULL, source text NOT NULL, supersedes bigint, UNIQUE(run_id,entity_id,revision));
CREATE TABLE IF NOT EXISTS commands(id text PRIMARY KEY, run_id text REFERENCES runs(id), actor text NOT NULL, expected_revision bigint NOT NULL, payload jsonb NOT NULL, status text NOT NULL, result jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS outbox(id bigserial PRIMARY KEY, command_id text UNIQUE REFERENCES commands(id), status text NOT NULL DEFAULT 'queued', attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), last_error text);
CREATE INDEX IF NOT EXISTS outbox_ready ON outbox(available_at) WHERE status='queued';
CREATE TABLE IF NOT EXISTS plans(id text PRIMARY KEY, run_id text REFERENCES runs(id), base_revision bigint NOT NULL, policy text NOT NULL, status text NOT NULL DEFAULT 'proposed', evidence jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS experiments(id text PRIMARY KEY, run_id text REFERENCES runs(id), base_revision bigint NOT NULL, snapshot jsonb NOT NULL, status text NOT NULL DEFAULT 'queued', progress integer NOT NULL DEFAULT 0, manifest jsonb NOT NULL, result jsonb, error text, attempts integer NOT NULL DEFAULT 0, lease_until timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS source_assertions(id text PRIMARY KEY, title text NOT NULL, source text NOT NULL, review_status text NOT NULL, executable boolean NOT NULL DEFAULT false, body text NOT NULL, CHECK(NOT executable OR review_status='reviewed'));
INSERT INTO source_assertions VALUES
 ('R-STACK','Accessible cargo only','Fictional terminal operating contract v1','reviewed',true,'A yard pickup requires the top container. Predecessors complete before retrieval. This fixture is not a certified terminal policy.'),
 ('R-CAPACITY','Reserve destination capacity','Fictional terminal operating contract v1','reviewed',true,'In-flight moves reserve destination space before dispatch. Each equipment unit can serve one move at a time.'),
 ('R-AUTHORITY','Release is separate from readiness','Fictional terminal operating contract v1','reviewed',true,'Only the scenario administrator injects synthetic release observations. A planner cannot clear an authority hold by approving a plan.'),
 ('DCSA','Shipment, equipment and transport events','https://dcsa.org/standards/track-and-trace','reference',false,'Terminology reference only. The local event envelope is not certified DCSA API conformance.'),
 ('R-TIME','Separate event time from knowledge time','Local temporal evidence contract v1','reviewed',true,'Late observations retain their event minute and recording revision. Prior snapshots remain immutable. Historical observations do not rewrite completed physical moves.'),
 ('R-DURATION','Handling-time assumptions','Synthetic fixture v1','assumption',false,'Base durations are 3–7 simulated minutes plus one transfer minute. Deterministic per-job noise is ±20 percent. These are not calibrated handling rates.')
ON CONFLICT DO NOTHING;
INSERT INTO schema_version(version) VALUES(1) ON CONFLICT DO NOTHING;
