import {chromium,request} from 'playwright';
import fs from 'node:fs/promises';
const base=process.env.TERMINAL_TEST_URL || 'http://127.0.0.1:8790',out=process.env.TERMINAL_AUDIT_DIR || '../docs/operational-model';
await fs.mkdir(out,{recursive:true});
const check=(v,m)=>{if(!v)throw Error(m)};
const api=await request.newContext({baseURL:base,timeout:120000});
const login=await api.post('/api/session',{data:{code:(await fs.readFile(process.env.TERMINAL_ADMIN_CODE_FILE || '../.local/admin-code','utf8')).trim()}});
const {csrf}=await login.json(),headers={'X-CSRF-Token':csrf};
const post=async(path,data)=>{const r=await api.post(path,{headers,data});check(r.ok(),await r.text());return r.json()};
const packs=await(await api.get('/api/datasets')).json(),pack=packs.find(p=>p.id==='movement-shift');
const {id:run}=await post('/api/datasets/import',{pack_id:pack.id,expected_digest:pack.digest,request_id:crypto.randomUUID()});
const url=`${base}/?run=${run}&departure=NORTH-RAIL&cargo=CT-0121&page=Operations`;
await fs.writeFile(out+'/walkthrough.json',JSON.stringify({run,url},null,2));
const browser=await chromium.launch({headless:true});
try {
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);await page.getByRole('heading',{name:'North Rail',exact:true}).waitFor();
await page.locator('.case-map').screenshot({path:out+'/01-routes.png'});
await page.getByRole('button',{name:/Relocate container 122/}).click();
await page.getByRole('button',{name:'Inspect required work',exact:true}).click();
await page.getByRole('region',{name:'Movement and custody'}).screenshot({path:out+'/02-movement.png'});
check(await page.getByRole('region',{name:'Movement and custody'}).getByText('Empty reposition',{exact:false}).count(),'empty travel visible');
await page.getByRole('button',{name:'Compare destinations',exact:true}).click();
await page.locator('.placement-options').waitFor({timeout:120000});
await page.locator('.placement-options button').first().click();
await page.getByText('Planned stack occupancy',{exact:true}).waitFor();
await page.locator('.placement').screenshot({path:out+'/03-placement.png'});
await page.getByRole('button',{name:'3 Compare & book',exact:true}).click();
await page.getByRole('button',{name:'Build recovery schedules',exact:true}).click();
await page.locator('.schedule-candidates').waitFor({timeout:120000});
check(await page.locator('.schedule-choice').count()===3,'all strategies visible');
await page.locator('.schedule-candidates').screenshot({path:out+'/04-comparison.png'});
await page.locator('.schedule-timeline').screenshot({path:out+'/05-stage-bookings.png'});
await page.getByText('Assumptions, solver status and limits',{exact:true}).click();
check(errors.length===0,'no errors opening solver detail: '+errors.join(';'));
await page.setViewportSize({width:800,height:900});
await page.getByRole('button',{name:'2 Required work',exact:true}).click();
await page.screenshot({path:out+'/06-compact.png'});
check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no viewport overflow');
await page.setViewportSize({width:1440,height:1000});
// Preserve the pristine review shift; execute on a branch.
const {id:branch}=await post('/api/runs?run='+run,{name:'Movement audit execution',fresh:false,profile:'standard'});
const req=await post('/api/schedules?run='+branch,{expected_revision:0,focus_commitment:'NORTH-RAIL',horizon:80});
let result;
for(let i=0;i<240;i++){const rows=await(await api.get('/api/schedules?run='+branch)).json();result=rows.find(r=>r.id===req.id);if(result?.status==='completed')break;if(result?.status==='failed')throw Error(result.error);await new Promise(r=>setTimeout(r,500));}
check(result?.status==='completed','branch schedule finished');
const plan=result.result.candidates.find(c=>c.key==='deadline'&&c.validation==='passed');check(plan,'feasible deadline schedule');
const state=async()=> (await api.get('/api/state?run='+branch)).json();
async function command(action,extra={}){let before=await state();await post('/api/commands?run='+branch,{action,command_id:crypto.randomUUID(),expected_revision:before.revision,...extra});for(let i=0;i<100;i++){const s=await state();if(s.revision>before.revision)return s;await new Promise(r=>setTimeout(r,100));}throw Error('command not acknowledged '+action);}
await command('approve_schedule',{plan_id:plan.plan_id});
let live=await command('advance',{minutes:8});
const cargo=live.containers.find(c=>c.custody?.kind==='equipment'&&c.custody.id.startsWith('TT'));
check(cargo,'cargo on a tractor');const job=live.jobs.find(j=>j.id===cargo.job_id);
const receiver=job.movement_stages.find(p=>p.kind==='setdown').resources.find(e=>!e.startsWith('TT'));
live=await command('fail',{entity_id:receiver});
check(live.schedule.status==='interrupted','failure interrupts');
check(live.containers.find(c=>c.id===cargo.id).custody.id===cargo.custody.id,'custody preserved');
const branchUrl=`${base}/?run=${branch}&departure=NORTH-RAIL&cargo=${cargo.id}&page=Operations&stage=Execution`;
await page.goto(branchUrl);await page.getByRole('region',{name:'Movement and custody'}).waitFor();
await page.getByRole('region',{name:'Movement and custody'}).screenshot({path:out+'/07-interrupted-custody.png'});
await page.locator('.schedule-timeline').screenshot({path:out+'/08-released-bookings.png'});
await page.getByRole('button',{name:'Scenario lab',exact:true}).click();
await page.getByRole('heading',{name:'Route availability',exact:true}).waitFor();
await page.screenshot({path:out+'/09-route-controls.png'});
check(errors.length===0,errors.join(';'));
await fs.writeFile(out+'/browser-audit.json',JSON.stringify({run,url,branch,branchUrl,receiver,cargo:cargo.id,checks:['case selection','metric routes','empty travel','SQL occupancy','three strategies','solver details','compact viewport','approval on branch','stage execution','failure preserves custody','route controls'],errors},null,2));
console.log(JSON.stringify({run,url,branch,errors}));
} finally { await browser.close();await api.dispose(); }
