import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const out='../docs/relationship-upgrade';await fs.mkdir(out,{recursive:true});
const check=(value,message)=>{if(!value)throw Error(message)};
async function stateAt(run,revision){
 for(let i=0;i<100;i++){
  const response=await page.request.get('http://127.0.0.1:8790/api/state?run='+run);
  const s=await response.json();
  if(s.revision===revision)return s;
  await new Promise(r=>setTimeout(r,100));
 }
 throw Error('Revision did not settle: '+revision);
}
await page.goto('http://127.0.0.1:8790',{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Terminal overview',exact:true}).click();
await page.getByRole('heading',{name:'One terminal. Connected decisions.'}).waitFor();
await page.getByRole('button',{name:'Explore starting state · 08:00'}).click();
await page.getByText('Read-only snapshot · revision 0').waitFor();
await page.getByRole('button',{name:'Inspect AURORA',exact:true}).click();
await page.locator('.inspector').getByText('Currently aboard · 6').waitFor();
await page.locator('.inspector').getByRole('button',{name:/CT-0133 · import/}).click();
await page.locator('.inspector h2').filter({hasText:'CT-0133'}).waitFor();
check((await page.locator('.inspector').innerText()).includes('MV-014'),'Cargo journey missing discharge');
await page.screenshot({path:out+'/01-import-journey.png',fullPage:true});
await page.locator('.inspector .work-card').filter({hasText:'MV-015'}).click();
check((await page.locator('.inspector').innerText()).includes('Not started'),'Queued timing misleading');
check(!(await page.locator('.inspector').innerText()).includes('Another container is stacked above'),'False vessel stack blocker');
await page.getByRole('button',{name:'Trace relationships & evidence'}).click();
await page.getByRole('heading',{name:'Every decision has a history.'}).waitFor();
check((await page.locator('.relationship-list').innerText()).includes('CT-0133'),'Evidence lost cargo link');
check((await page.locator('.clockbar').innerText()).includes('revision 0'),'Evidence lost historical context');
await page.screenshot({path:out+'/02-evidence.png',fullPage:true});
await page.getByRole('button',{name:'Close inspector'}).click();
await page.getByRole('button',{name:'Scenario lab',exact:true}).click();
await page.getByLabel('Scenario administrator code').fill((await fs.readFile('../.local/admin-code','utf8')).trim());
await page.getByRole('button',{name:'Unlock scenario controls'}).click();
const created=page.waitForResponse(r=>r.url().includes('/api/runs?')&&r.request().method()==='POST');
await page.getByRole('button',{name:'New standard shift · 144 containers'}).click();
const run=(await (await created).json()).id;
await page.waitForFunction(run=>document.querySelector('[aria-label="Active shift"]').value===run,run);
await page.getByRole('button',{name:'Inspect AURORA',exact:true}).click();
await page.locator('.inspector').getByText('Currently aboard · 6').waitFor();
await page.screenshot({path:out+'/03-vessel-manifest.png',fullPage:true});
await page.getByRole('button',{name:'Close inspector'}).click();
await page.getByRole('button',{name:'Scenario lab',exact:true}).click();
await page.getByLabel('Pickup to obstruct').selectOption('MV-003');
await page.getByRole('button',{name:'Inject synthetic cover',exact:true}).click();
await stateAt(run,1);
await page.getByRole('button',{name:'Recovery',exact:true}).click();
await page.getByText('Additional tools · access relocations and policy experiments',{exact:true}).click();
await page.getByRole('button',{name:'Preview access plan for CT-0123'}).click();
await page.getByRole('button',{name:'Approve these prerequisite jobs'}).waitFor();
await page.screenshot({path:out+'/04-access-proposal.png',fullPage:true});
await page.getByRole('button',{name:'Approve these prerequisite jobs'}).click();
const state=await stateAt(run,2);
check(state.jobs.length===38,`Access job not persisted: ${JSON.stringify({run,revision:state.revision,jobs:state.jobs.length})}`);
check(state.containers.find(c=>c.id==='CT-0123').location_id==='A3','Approval moved cargo');
await page.getByRole('button',{name:'Scenario lab',exact:true}).click();
await page.getByRole('button',{name:'Validate and retain input'}).click();
await page.getByRole('status').filter({hasText:'Recorded.'}).waitFor();
await page.screenshot({path:out+'/05-scenario-impact.png',fullPage:true});
await page.getByRole('button',{name:'Evidence',exact:true}).click();
await page.getByText('equipment-feed-rehearsal / event-001 · accepted').waitFor();
await page.getByRole('button',{name:'Recovery',exact:true}).click();
await page.getByText('Additional tools · access relocations and policy experiments',{exact:true}).click();
await page.getByRole('button',{name:'Compare plans',exact:true}).click();
await page.getByRole('heading',{name:/Recovery alternatives/}).waitFor({timeout:120000});
await page.screenshot({path:out+'/06-recovery.png',fullPage:true});
// Check narrow layout has no page-wide horizontal overflow.
await page.setViewportSize({width:1100,height:900});
await page.getByRole('button',{name:'Operations',exact:true}).click();
check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Page overflow at laptop width');
await fs.writeFile(out+'/audit.json',JSON.stringify({run,errors,checks:['vessel manifests','cargo journey','historical evidence','false blocker removed','access preview and approval','provenance rehearsal','recovery comparison','1100px layout']},null,2));
console.log(JSON.stringify({run,errors}));
check(!errors.length,'Browser errors');await browser.close();
